# ejemplos con igraph
g1 <- aging.prefatt.game(10000, pa.exp=1, aging.exp=0, aging.bin=1000)
max(degree(g1))
g.1 <- graph( c(1,3,2,3,3,4,4,5) )
alpha.centrality(g.1)
articulation.points(g.1)
as.directed(g.1, mode = c("mutual", "arbitrary"))
as.undirected(g.1, mode = c("collapse", "each", "mutual"),edge.attr.comb = getIgraphOpt("edge.attr.comb"))
assortativity(g.1,3)
assortativity.degree(erdos.renyi.game(10000,3/10000))
g <- graph.ring(10)
g <- set.graph.attribute(g, "name", "RING")
g <- set.vertex.attribute(g, "color", value=c("red", "green"))
get.vertex.attribute(g, "color")
g <- set.edge.attribute(g, "weight", value=runif(ecount(g)))
get.edge.attribute(g, "weight")
betweenness(g)
edge.betweenness(g)
biconnected.components(g)
bipartite.mapping(g)
g <- graph.full.bipartite(10,5)
proj <- bipartite.projection(g)
graph.isomorphic(proj[[1]], graph.full(10))
g <- graph.ring(10)
closeness(g)
clusters(g)
is.connected(g)
no.clusters(g)
cluster.distribution(g)
cocitation(g)
bibcoupling(g)
cohesive.blocks(g, labels = TRUE)
mwBlocks <- cohesive.blocks(g)
mwBlocks
mwBlocks
blocks(mwBlocks)
cohesion(mwBlocks)
karate <- graph.famous("Zachary")
wc <- walktrap.community(karate)
modularity(wc)
membership(wc)
plot(wc, karate)


